"""initial schema

Revision ID: 0000
Revises:
Create Date: 2026-07-09

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0000"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector is required by fragment_embeddings.embedding (VECTOR column) below.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("resource", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_name"), "permissions", ["name"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cognito_sub", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_cognito_sub"), "users", ["cognito_sub"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("notification_type", sa.String(length=32), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_notifications_created_at", "notifications", ["created_at"], unique=False)
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"], unique=False)
    op.create_index(
        "ix_notifications_user_id_is_read", "notifications", ["user_id", "is_read"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("llm_provider", sa.String(length=100), nullable=True),
        sa.Column("llm_model", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("project_type", sa.String(length=50), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "owner_id", name="uq_project_name_owner"),
    )
    op.create_index(op.f("ix_projects_deleted_at"), "projects", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_index(op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("assigned_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["assigned_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "incremental_histories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("updates_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("adds_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("delete_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("flag_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "persona_glossary_additions_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("meeting_summary_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incremental_histories_project_id"),
        "incremental_histories",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_incremental_histories_project_id_created_at",
        "incremental_histories",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "project_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_code", sa.String(length=20), nullable=False),
        sa.Column("stages", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_code"),
    )
    op.create_index(
        "ix_project_runs_project_id_status", "project_runs", ["project_id", "status"], unique=False
    )
    op.create_table(
        "source_ingestions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "rfp",
                "additional_rfp",
                "source_code",
                "meeting_notes",
                "requirement_update",
                name="source_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("stages", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_language", sa.String(length=255), nullable=True),
        sa.Column("frontend_stack", sa.String(length=255), nullable=True),
        sa.Column("backend_stack", sa.String(length=255), nullable=True),
        sa.Column("infrastructure_stack", sa.String(length=255), nullable=True),
        sa.Column("architecture_stack", sa.String(length=255), nullable=True),
        sa.Column("database_stack", sa.String(length=255), nullable=True),
        sa.Column("coding_standard", sa.String(length=255), nullable=True),
        sa.Column("database_strategy", sa.String(length=255), nullable=True),
        sa.Column("architecture", sa.String(length=255), nullable=True),
        sa.Column("security", sa.String(length=255), nullable=True),
        sa.Column("is_incremental", sa.Boolean(), nullable=True),
        sa.Column("user_message", sa.Text(), nullable=True),
        sa.Column("skip_processing", sa.Boolean(), nullable=False),
        sa.Column("sc_architecture_type", sa.String(length=32), nullable=True),
        sa.Column("tot_modules", sa.Integer(), nullable=False),
        sa.Column("tot_features", sa.Integer(), nullable=False),
        sa.Column("tot_user_stories", sa.Integer(), nullable=False),
        sa.Column("mod_fea_gen_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mod_fea_gen_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_story_gen_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_story_gen_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_ingestions_project_id"), "source_ingestions", ["project_id"], unique=False
    )
    op.create_index(
        "ix_source_ingestions_project_id_deleted_at",
        "source_ingestions",
        ["project_id", "deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_source_ingestions_project_id_status",
        "source_ingestions",
        ["project_id", "status"],
        unique=False,
    )
    op.create_table(
        "project_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("task_type", sa.String(length=64), nullable=False),
        sa.Column("celery_task_id", sa.String(length=256), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=256), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["project_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("celery_task_id"),
    )
    op.create_index(
        "ix_project_tasks_celery_task_id", "project_tasks", ["celery_task_id"], unique=False
    )
    op.create_index(
        "ix_project_tasks_project_id_status",
        "project_tasks",
        ["project_id", "status"],
        unique=False,
    )
    op.create_index("ix_project_tasks_run_id", "project_tasks", ["run_id"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("original_name", sa.String(length=512), nullable=False),
        sa.Column("relative_path", sa.String(length=2048), nullable=True),
        sa.Column("storage_key", sa.String(length=1024), nullable=True),
        sa.Column("storage_url", sa.Text(), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("file_type", sa.String(length=32), nullable=False),
        sa.Column("upload_type", sa.String(length=16), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("source_ingestion_id", sa.UUID(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "rfp",
                "additional_rfp",
                "source_code",
                "meeting_notes",
                "requirement_update",
                name="source_type_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "queued",
                "processing",
                "running",
                "ready_for_review",
                "change_set_ready",
                "applied",
                "completed",
                "failed",
                name="source_processing_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("applied_version", sa.Integer(), nullable=True),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("link_url", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_ingestion_id"], ["source_ingestions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sources_batch_id"), "sources", ["batch_id"], unique=False)
    op.create_index(
        op.f("ix_sources_checksum_sha256"), "sources", ["checksum_sha256"], unique=False
    )
    op.create_index(op.f("ix_sources_created_by"), "sources", ["created_by"], unique=False)
    op.create_index(op.f("ix_sources_id"), "sources", ["id"], unique=False)
    op.create_index(op.f("ix_sources_project_id"), "sources", ["project_id"], unique=False)
    op.create_index(
        "ix_sources_project_id_is_deleted", "sources", ["project_id", "is_deleted"], unique=False
    )
    op.create_index(
        "ix_sources_project_id_status", "sources", ["project_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_sources_source_ingestion_id"), "sources", ["source_ingestion_id"], unique=False
    )
    op.create_table(
        "fragment_embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("fragment_id", sa.String(length=36), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fragment_embeddings_fragment_id"),
        "fragment_embeddings",
        ["fragment_id"],
        unique=False,
    )
    op.create_index(op.f("ix_fragment_embeddings_id"), "fragment_embeddings", ["id"], unique=False)
    op.create_index(
        op.f("ix_fragment_embeddings_project_id"),
        "fragment_embeddings",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fragment_embeddings_source_id"), "fragment_embeddings", ["source_id"], unique=False
    )
    op.create_index(
        "uq_fragment_embeddings_source_fragment",
        "fragment_embeddings",
        ["source_id", "fragment_id"],
        unique=True,
    )
    op.create_table(
        "project_task_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=256), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["project_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_project_task_events_project_id_created_at",
        "project_task_events",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_project_task_events_project_id_status",
        "project_task_events",
        ["project_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_project_task_events_task_id_created_at",
        "project_task_events",
        ["task_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "story_feedback_histories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("task_db_id", sa.UUID(), nullable=True),
        sa.Column(
            "story_feedbacks_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Input list of story + feedback items sent to the AI patch pipeline",
        ),
        sa.Column(
            "revised_stories_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="AI-revised story list (revised_stories) from the patch output",
        ),
        sa.Column(
            "ai_status",
            sa.String(length=32),
            nullable=True,
            comment="PASS | FAIL | UNKNOWN — critic gate result",
        ),
        sa.Column(
            "ai_feedback",
            sa.Text(),
            nullable=True,
            comment="Critic suggested-fix text; empty string on PASS",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_db_id"], ["project_tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_story_feedback_histories_project_id"),
        "story_feedback_histories",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_story_feedback_histories_project_id_created_at",
        "story_feedback_histories",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_story_feedback_histories_task_db_id"),
        "story_feedback_histories",
        ["task_db_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_story_feedback_histories_task_db_id"), table_name="story_feedback_histories"
    )
    op.drop_index(
        "ix_story_feedback_histories_project_id_created_at", table_name="story_feedback_histories"
    )
    op.drop_index(
        op.f("ix_story_feedback_histories_project_id"), table_name="story_feedback_histories"
    )
    op.drop_table("story_feedback_histories")
    op.drop_index("ix_project_task_events_task_id_created_at", table_name="project_task_events")
    op.drop_index("ix_project_task_events_project_id_status", table_name="project_task_events")
    op.drop_index("ix_project_task_events_project_id_created_at", table_name="project_task_events")
    op.drop_table("project_task_events")
    op.drop_index("uq_fragment_embeddings_source_fragment", table_name="fragment_embeddings")
    op.drop_index(op.f("ix_fragment_embeddings_source_id"), table_name="fragment_embeddings")
    op.drop_index(op.f("ix_fragment_embeddings_project_id"), table_name="fragment_embeddings")
    op.drop_index(op.f("ix_fragment_embeddings_id"), table_name="fragment_embeddings")
    op.drop_index(op.f("ix_fragment_embeddings_fragment_id"), table_name="fragment_embeddings")
    op.drop_table("fragment_embeddings")
    op.drop_index(op.f("ix_sources_source_ingestion_id"), table_name="sources")
    op.drop_index("ix_sources_project_id_status", table_name="sources")
    op.drop_index("ix_sources_project_id_is_deleted", table_name="sources")
    op.drop_index(op.f("ix_sources_project_id"), table_name="sources")
    op.drop_index(op.f("ix_sources_id"), table_name="sources")
    op.drop_index(op.f("ix_sources_created_by"), table_name="sources")
    op.drop_index(op.f("ix_sources_checksum_sha256"), table_name="sources")
    op.drop_index(op.f("ix_sources_batch_id"), table_name="sources")
    op.drop_table("sources")
    op.drop_index("ix_project_tasks_run_id", table_name="project_tasks")
    op.drop_index("ix_project_tasks_project_id_status", table_name="project_tasks")
    op.drop_index("ix_project_tasks_celery_task_id", table_name="project_tasks")
    op.drop_table("project_tasks")
    op.drop_index("ix_source_ingestions_project_id_status", table_name="source_ingestions")
    op.drop_index("ix_source_ingestions_project_id_deleted_at", table_name="source_ingestions")
    op.drop_index(op.f("ix_source_ingestions_project_id"), table_name="source_ingestions")
    op.drop_table("source_ingestions")
    op.drop_index("ix_project_runs_project_id_status", table_name="project_runs")
    op.drop_table("project_runs")
    op.drop_index(
        "ix_incremental_histories_project_id_created_at", table_name="incremental_histories"
    )
    op.drop_index(op.f("ix_incremental_histories_project_id"), table_name="incremental_histories")
    op.drop_table("incremental_histories")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_deleted_at"), table_name="projects")
    op.drop_table("projects")
    op.drop_index("ix_notifications_user_id_is_read", table_name="notifications")
    op.drop_index("ix_notifications_user_id", table_name="notifications")
    op.drop_index("ix_notifications_created_at", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_cognito_sub"), table_name="users")
    op.drop_table("users")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
