"""SQLAlchemy ORM model for Project.

A Project is the top-level organisational unit in RIP.  All source
uploads are scoped to a project so that requirement
extraction, de-duplication, and downstream sync are always isolated
per project.

Relationships
─────────────
User ──< Project          (owner FK)
Tenant ──< Project        (tenant FK — nullable, MVP single-tenant deployments)
Project ──< Source        (one project → many ingested sources)
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING
import uuid

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.constants import INITIAL_ENTITY_VERSION
from app.core.enums.project_status import ProjectStatus
from app.db.base import Base

if TYPE_CHECKING:
    from app.models.postgres.tenant_model import Tenant
    from app.models.postgres.user_model import User


class Project(Base):
    __tablename__ = "projects"
    __table_args__ = (
        # Enforces name uniqueness per owner at the DB level, preventing
        # TOCTOU race conditions that application-level checks cannot stop.
        UniqueConstraint("name", "owner_id", name="uq_project_name_owner"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    # Short, human-readable identifier: "{tenant.code}-{seq:04d}" for tenanted
    # projects, or "PRJ-{seq:04d}" for untenanted ones (MVP single-tenant
    # deployments) — see ProjectService._generate_project_code. Assigned once
    # at creation and immutable.
    code: Mapped[str] = mapped_column(String(30), nullable=False, unique=True, index=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    llm_provider: Mapped[str | None] = mapped_column(String(100), nullable=True)
    llm_model: Mapped[str | None] = mapped_column(String(255), nullable=True)
    status: Mapped[str] = mapped_column(
        String(50), nullable=False, default=ProjectStatus.ACTIVE.value
    )
    project_type: Mapped[str | None] = mapped_column(String(50), nullable=True, default=None)
    # Bumped by 1 on every update that changes a mutable field, mirroring the
    # Module/Feature/UserStory version-counter convention (see
    # app.core.constants.INITIAL_ENTITY_VERSION). Not a history/audit trail —
    # just a change counter.
    version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=INITIAL_ENTITY_VERSION,
        server_default=str(INITIAL_ENTITY_VERSION),
    )
    owner_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    # Nullable — MVP single-tenant deployments have no tenant assigned, same
    # as users.tenant_id. Auto-derived from the owner's tenant at creation
    # time; not yet used to scope any queries (see Tenant model docstring).
    tenant_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        # NOTE: onupdate=func.now() is a client-side SQLAlchemy hook, NOT a
        # database-level trigger.  It fires only for ORM UPDATE statements
        # generated by this session.  Rows updated via raw SQL (e.g. Alembic
        # data migrations, direct psql) will NOT have updated_at refreshed.
        # If you need a guaranteed server-side timestamp, add a PostgreSQL
        # trigger: CREATE TRIGGER set_updated_at ... BEFORE UPDATE ON projects
        onupdate=func.now(),
        nullable=False,
    )
    # Soft-delete: set to the current timestamp instead of hard-deleting rows.
    # Queries that should exclude deleted projects must filter
    # ``Project.deleted_at.is_(None)``.  Hard deletes (via DELETE cascade) are
    # used only for test cleanup or data-retention purges.
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None, index=True
    )
    # Timestamp of the most recent ActivityLog entry recorded for this
    # project (set by ActivityLogService.record_activity, the sole
    # ActivityLog write path) — None until the first activity is logged.
    last_activity_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )

    owner: Mapped[User | None] = relationship(
        "User",
        foreign_keys=[owner_id],
        # lazy="raise" prevents accidental N+1 queries: any code that touches
        # project.owner outside an explicit joinedload() will raise an error
        # at runtime, making silent performance regressions impossible.
        lazy="raise",
    )
    tenant: Mapped[Tenant | None] = relationship(
        "Tenant",
        foreign_keys=[tenant_id],
        lazy="raise",
    )
